#cloud-config

write_files:
  - path: /etc/sysctl.conf
    content: |
      net.ipv6.conf.all.forwarding = 1
      net.ipv4.ip_forward = 1
    owner: root:root
    permissions: '644'
    defer: false
    append: true
  - path: /etc/wireguard/postup.sh
    content: |
      #!/bin/bash
      iptables -A FORWARD -i $1 -j ACCEPT
      iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
      iptables -t nat -A POSTROUTING -o $1 -j MASQUERADE
      ip6tables -A FORWARD -i $1 -j ACCEPT
    owner: root:root
    permissions: '500'
    defer: false
    append: true
  - path: /etc/wireguard/postdown.sh
    content: |
      #!/bin/bash
      iptables -D FORWARD -i $1 -j ACCEPT
      iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE
      iptables -t nat -D POSTROUTING -o $1 -j MASQUERADE
      ip6tables -D FORWARD -i $1 -j ACCEPT
    owner: root:root
    permissions: '500'
    defer: false
    append: true
  - path: /etc/wireguard/wg0.conf
    content: |
      [Interface]
      PrivateKey = WG_PRIV_KEY
      PostUp = /etc/wireguard/postup.sh "%i"
      PostDown = /etc/wireguard/postdown.sh "%i"

      # Wireguard internal network. Can't overlap with home network
      Address = ${wireguard_cidr}
      ListenPort = ${wireguard_port}
      [Peer]
      # External host
      PublicKey = ${wan_wg_public_key}
      AllowedIPs = ${wan_peer}
      [Peer]
      # Machine to VPN to
      PublicKey = ${internal_wg_public_key}
      AllowedIPs = ${lan_peer}%{ for cidr in lan_cidrs },${cidr}%{ endfor }
    owner: root:root
    permissions: '600'
    defer: false
    append: false

packages:
  - wireguard-tools
  - iptables
  - ufw
  - unzip

runcmd:
  - curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "/tmp/awscliv2.zip"
  - unzip -qq /tmp/awscliv2.zip -d /tmp
  - /tmp/aws/install
  - rm -rf /tmp/aws /tmp/aws/awscliv2.zip
  - WG_PRIV_KEY=$(wg genkey)
  - sed -i "s^WG_PRIV_KEY^$WG_PRIV_KEY^g" /etc/wireguard/wg0.conf
  - WG_PUB_KEY=$(printf '%s' "$WG_PRIV_KEY" | wg pubkey)
  - aws ssm put-parameter --name '${pub_key_param.name}' --type ${pub_key_param.type} --value "$WG_PUB_KEY" --overwrite --output text --no-cli-pager
  - sysctl -p
  - systemctl enable --now wg-quick@wg0.service
